spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/plusa?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  config:
    activate:
      on-profile: dev
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 8000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 50
        max-wait: -1
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
server:
  port: 8082
xjj:
  imgfilepath: "D:/图片/"
  secret: "5s15d1512S3Sss8323657ecjkhdefdafaefsgevdsD"
